# Generated by Django 6.0 on 2025-12-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encryptionKey',
        ),
    ]
