# Generated by Django 6.0 on 2026-06-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0002_delete_encryptionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
