# Generated by Django 6.0 on 2025-12-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_encryptionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
